### ISSUE TITLE
wrong count

### ISSUE THREAD

**Issue by davidp88** [brandon1024/find#393]
Open this site- https://www.gpsoft.com.au/program/program.html and search for "opus",there are only 14 matches for opus but find shows 16 matches found.Even firefox says 14 matches only.

**Comment by Aybee** [comment]
It also finds occurrences that are hidden by CSS. Sometimes this can also be an advantage.

**Comment by davidp88** [comment]
Showing matches that are hidden by Css is not correct,pls exclude matches that are hidden by css

**Comment by brandon1024** [comment]
The two extra occurrences are from the navbar, which have a `visibility: hidden` style applied to them. In the extensions plugin scripts, [isHiddenElement](https://github.com/brandon1024/find/blob/develop/content/parser.js#L256) doesn't account for this. Easy fix.

**Comment by Aybee** [comment]
There are many other ways to hide elements from visibility. E.g. this often used class to show elements only to screenreaders from Contao CMS
```css
.invisible {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}
```
or this from Bootstrap
```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
```
But there are many others
```css
Element {
	overflow: hidden;
	text-indent: 100%;
}
Element {
	position: absolute;
	z-index: -1;
}
Element {
	position: absolute;
	left: -10000px;
}
Element {
	height: 0;
	overflow: hidden;
}
```
And more ...

You can find many approaches on the web to find out whether the visitor sees an element or rather a text or not. I think they can all fail somehow. So this ticket is definitely not a bug.
